export const courseMap = {
  CER: {
    1: [
      {
        name: "PHY102: Physics - II: Introduction to Engineering Electromagnetics",
        credits: 13,
      },
      { name: "CY101: Chemistry - I", credits: 10 },
      { name: "MA102: Engineering Mathematics - II", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "ME104: Engineering Drawing", credits: 6 },
      { name: "ME105: Manufacturing Practice - I", credits: 3 },
    ],
    2: [
      {
        name: "H-103: Development of Societies/History and Civilization",
        credits: 8,
      },
      {
        name: "PHY101: Physics - I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "MA101: Engineering Mathematics – I", credits: 11 },
      { name: "ME103: Engineering Thermodynamics", credits: 11 },
      { name: "MCR101: Introduction to Ceramics", credits: 6 },
      { name: "MCR102: Basic Ceramic Practices", credits: 6 },
      { name: "ME106: Manufacturing Practice - II", credits: 3 },
    ],
    3: [
      { name: "Philosophy/Education and Self", credits: 8 },
      { name: "MO201: Materials Science", credits: 11 },
      { name: "MCR201: Ceramic Raw Materials", credits: 11 },
      {
        name: "MCR202: Thermodynamics and Phase Equilibria in Ceramic Systems",
        credits: 9,
      },
      {
        name: "MCR203: Particle Mechanics and Fluid Flow Process",
        credits: 11,
      },
      { name: "MCR292: Minerology and Microscopy Lab", credits: 2 },
    ],
    4: [
      { name: "MA203: Mathematical Methods", credits: 11 },
      { name: "EO101: Fundamental of Electrical Engineering", credits: 13 },
      { name: "CHO101: Heat and Mass Transfer", credits: 11 },
      {
        name: "MCR204: Structure and Properties of Ceramic Materials",
        credits: 9,
      },
      {
        name: "MCR205: Ceramic Phase Diagrams and Phase Transformation",
        credits: 9,
      },
      { name: "MCR291: Exploratory Project", credits: 5 },
    ],
    5: [
      { name: "MCR301: Techniques for Materials Characterization", credits: 9 },
      { name: "MCR304: Ceramic Processing", credits: 9 },
      { name: "MCR311: Glass and Glass Ceramics", credits: 11 },
      { name: "MCR321: Refractories", credits: 11 },
      { name: "MCR331: Advanced Ceramics", credits: 11 },
      { name: "OE - 1: Open Elective - 1", credits: 9 },
      { name: "MCR392: UG Project", credits: 10 },
    ],
    6: [
      { name: "MCR302: Process Calculations", credits: 6 },
      { name: "MCR303: Ceramic Whitewares", credits: 11 },
      { name: "MCR402: Cement and Concrete", credits: 11 },
      { name: "DE - 1: Department Elective (DE) - 1", credits: 11 },
      { name: "OE - 2: Open Elective - 2", credits: 9 },
      { name: "MCR392/MCR392S: UG Project", credits: 10 },
    ],
    7: [
      { name: "MCR401: Fuel, Furnace & Pyrometry", credits: 11 },
      { name: "DE - 2: Department Elective (DE) - 2", credits: 9 },
      { name: "DE - 3: Department Elective (DE) - 3", credits: 9 },
      { name: "OE - 3: Open Elective - 3", credits: 9 },
      { name: "LM: Language & Management Course", credits: 9 },
      { name: "MCR491/MCR491S: Stream or UG Project", credits: 10 },
    ],
    8: [
      { name: "MCR404: Plant, Equipment and Furnace Design", credits: 9 },
      { name: "DE - 4: Department Elective (DE) - 4", credits: 9 },
      { name: "DE - 5: Department Elective (DE) - 5", credits: 9 },
      { name: "OE - 4: Open Elective - 4", credits: 9 },
      { name: "LM: Language & Management Course", credits: 9 },
    ],
  },
  CHE: {
    1: [
      { name: "CHO-103: Process Calculations", credits: 8 },
      { name: "ME-105: Manufacturing Practice-I", credits: 3 },
      { name: "ME-103: Engineering Thermodynamics", credits: 11 },
      { name: "MA-102: Engineering Mathematics-II", credits: 11 },
      { name: "CY-101: Chemistry-I", credits: 10 },
      { name: "PHY-101: Physics-I", credits: 13 },
    ],
    2: [
      {
        name: "H-103: Development of Societies/History and Civilization",
        credits: 8,
      },
      { name: "ME-106: Manufacturing Practice-II", credits: 3 },
      { name: "CHE-101: Chemical Engineering Practices", credits: 6 },
      { name: "CHE-201: Chemical Engineering Thermodynamics", credits: 11 },
      { name: "CSO-101: Computer Programming", credits: 13 },
      { name: "ME-104: Engineering Drawing", credits: 6 },
      { name: "MA-101: Engineering Mathematics-I", credits: 11 },
    ],
    3: [
      { name: "Philosophy/Education and Self", credits: 8 },
      { name: "CHO-102: Fluid Mechanics", credits: 11 },
      { name: "CHE-291: Exploratory Project", credits: 5 },
      { name: "CHE-202: Fluid Flow and Mechanical Operations", credits: 8 },
      { name: "CHO-201: Chemical Reaction Engineering-I", credits: 8 },
      { name: "CHO-101: Heat and Mass Transfer", credits: 11 },
      { name: "MA-201: Numerical Techniques", credits: 11 },
    ],
    4: [
      { name: "Flexi-Core Course", credits: 9 },
      { name: "CHE-304: Process Dynamics & Control", credits: 9 },
      { name: "CHE-205: Fluid Flow and Mechanical Operations Lab", credits: 2 },
      { name: "CHE-204: Mass Transfer Operations-I", credits: 11 },
      { name: "CHE-203: Heat Transfer Operations", credits: 8 },
      { name: "CHO-204: Chemical Reaction Engineering Laboratory", credits: 2 },
      { name: "CHO-203: Chemical Reaction Engineering-II", credits: 8 },
      { name: "MO-241: Materials Science", credits: 11 },
    ],
    5: [
      { name: "CHO301: Chemical Technology", credits: 9 },
      { name: "CY103: Essentials of Biochemistry", credits: 11 },
      { name: "Flexi Core Course", credits: 9 },
      { name: "CHE302: Heat Transfer Operations Lab", credits: 2 },
      { name: "CHE402: Process Instrumentation", credits: 6 },
      {
        name: "CHE303: Chemical Technology & Instrumental Analysis Laboratory",
        credits: 2,
      },
      { name: "DE - 1: Department Elective (DE) - 1", credits: 9 },
      { name: "OE - 1: Open Elective - 1", credits: 9 },
    ],
    6: [
      { name: "CHE305: Mass Transfer Operations-II", credits: 9 },
      { name: "CHE303: Mass Transfer Operations Lab", credits: 2 },
      { name: "Flexi Core Course (Any one)*", credits: 9 },
      { name: "DE - 2: Department Elective (DE) - 2", credits: 9 },
      { name: "OE - 2: Open Elective - 2", credits: 9 },
      { name: "CHE401: Transport Phenomena", credits: 9 },
      { name: "CHE307: Industrial Pollution Control Laboratory", credits: 2 },
      { name: "CHE308: Energy Resources Laboratory", credits: 2 },
      { name: "CHE392: UG Project", credits: 10 },
    ],
    7: [
      { name: "CHE312: Process Engineering and Plant Design", credits: 9 },
      {
        name: "CHE403: Instrumentation & Process Control Laboratory",
        credits: 2,
      },
      { name: "DE - 3: Departmental Elective (DE) - 3", credits: 9 },
      { name: "OE - 3: Open Elective - 3", credits: 9 },
      { name: "LM: Language and Management Course", credits: 9 },
      { name: "CHE491: UG Project", credits: 10 },
    ],
    8: [
      { name: "CHE405: Modelling, Simulation and Optimization", credits: 9 },
      { name: "CHE404: CAD and Simulation Laboratory", credits: 2 },
      { name: "DE - 4: Departmental Elective (DE) - 4", credits: 9 },
      { name: "DE - 5: Departmental Elective (DE) - 5", credits: 9 },
      { name: "OE - 4: Open Elective - 4", credits: 9 },
      { name: "LM: Language and Management Course", credits: 9 },
    ],
  },
  CSE: {
    1: [
      { name: "BL101: Biology", credits: 11 },
      {
        name: "PHY101: Physics I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "MA101: Engineering Mathematics- I", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "ME106: Manufacturing Practices-II", credits: 3 },
    ],
    2: [
      { name: "MA102: Engineering Mathematics- II", credits: 11 },
      { name: "EO101: Fundamentals of Electrical Engineering", credits: 13 },
      { name: "CSE102: Data Structures", credits: 11 },
      { name: "CSE103: Information Technology Workshop (ITW)", credits: 9 },
      { name: "ME104: Engineering Drawing", credits: 6 },
      { name: "ME105: Manufacturing Practices – I", credits: 3 },
      { name: "H105/H106: Philosophy or Education & Self", credits: 8 },
    ],
    3: [
      { name: "MA202: Probability and Statistics", credits: 11 },
      { name: "ME102: Engineering Mechanics", credits: 11 },
      { name: "CSE201: Computer System Organization", credits: 11 },
      { name: "CSE202: Digital Logic Design and Microprocessors", credits: 11 },
      { name: "CSE203: Discrete Maths", credits: 9 },
      {
        name: "H103/H104: Development of Societies or History & Civilization",
        credits: 8,
      },
    ],
    4: [
      { name: "MA203: Mathematical Methods", credits: 11 },
      { name: "CSE204: Algorithms", credits: 11 },
      { name: "CSE205: Operating Systems", credits: 11 },
      { name: "CSE206: Computer Networks", credits: 11 },
      { name: "CSE207: Exploratory Project", credits: 5 },
    ],
    5: [
      { name: "MO201: Materials Science and Engineering", credits: 11 },
      { name: "CSE301: Computer Graphics", credits: 11 },
      { name: "CSE302: Database Management System", credits: 11 },
      { name: "DE-1: Department Elective – 1", credits: 9 },
      { name: "OE-1: Open Elective – 1", credits: 9 },
    ],
    6: [
      { name: "CSE303: Computer Architecture", credits: 11 },
      { name: "CSE304: Theory of Computation", credits: 9 },
      { name: "CSE305: Software Engineering", credits: 11 },
      { name: "CSE306: UG Project", credits: 10 },
      { name: "DE-2: Department Elective – 2", credits: 9 },
      { name: "OE-2: Open Elective – 2", credits: 9 },
    ],
    7: [
      { name: "CSE401: Compiler Design", credits: 11 },
      { name: "DE-3: Department Elective – 3", credits: 9 },
      { name: "OE-3: Open Elective – 3", credits: 9 },
      { name: "LM: Language Management Courses", credits: 9 },
      { name: "CSE402: UG Project", credits: 10 },
    ],
    8: [
      { name: "CSE403: Artificial Intelligence", credits: 11 },
      { name: "DE-4: Department Elective – 4", credits: 9 },
      { name: "OE-4: Open Elective – 4", credits: 9 },
      { name: "LM: Language Management Courses", credits: 9 },
      { name: "CSE404: Seminar", credits: 3 },
    ],
  },
  CIV: {
    1: [
      {
        name: "PHY101: Physics - I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "CY101: Chemistry - I", credits: 10 },
      { name: "MA101: Engineering Mathematics - I", credits: 11 },
      { name: "ME102: Engineering Mechanics", credits: 11 },
      { name: "ME104: Engineering Drawing", credits: 6 },
      { name: "ME106: Manufacturing Practice - II", credits: 3 },
    ],
    2: [
      { name: "MA102: Engineering Mathematics – II", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      {
        name: "EO101/102: Fundamentals of Electrical Engineering or Electronics and Instrumentation Engineering",
        credits: 13,
      },
      { name: "CE101: Basic Surveying", credits: 9 },
      { name: "CE102: Surveying Laboratory", credits: 3 },
      { name: "ME105: Manufacturing Practice – I", credits: 3 },
      { name: "H105/H106: Philosophy or Education and Self", credits: 8 },
    ],
    3: [
      { name: "CE201: Mechanics of Solids", credits: 8 },
      { name: "CE202: Engineering Geology", credits: 9 },
      { name: "CE203: Building Materials and Construction", credits: 6 },
      { name: "CE204: Concrete Laboratory", credits: 2 },
      { name: "CE205: Engineering Geology Laboratory", credits: 2 },
      {
        name: "MA201/MA202: Numerical Techniques/Probability and Statistics",
        credits: 11,
      },
      { name: "CHO102: Fluid Mechanics", credits: 11 },
      {
        name: "H103/H104: Development of Societies or History and Civilization",
        credits: 8,
      },
    ],
    4: [
      { name: "MA203/CY103: Mathematical Methods/Biochemistry", credits: 11 },
      { name: "CE221: Geotechnical Engineering – I", credits: 9 },
      { name: "CE231: Structural Mechanics - I", credits: 9 },
      { name: "CE241: Environmental Engineering-I", credits: 9 },
      { name: "CE251: Transportation Engineering - I", credits: 9 },
      { name: "CE206: Building Planning, Drawing and Estimation", credits: 3 },
      { name: "CE222: Geotechnical Engineering Laboratory", credits: 2 },
      { name: "CE242: Environmental Engineering Laboratory", credits: 2 },
      { name: "CE252: Transportation Engineering Laboratory", credits: 2 },
      { name: "CE291: Exploratory Project", credits: 5 },
    ],
    5: [
      { name: "CE321: Geotechnical Engineering-II", credits: 8 },
      { name: "CE351: Transportation Engineering-II", credits: 8 },
      { name: "CE331: Structural Mechanics - II", credits: 8 },
      { name: "CE332: Design of RC Structures", credits: 8 },
      { name: "CE441: Environmental Engineering-II", credits: 8 },
      { name: "DE-1: Department Elective (DE) - 1", credits: 9 },
      { name: "OE-1: Open Elective - 1", credits: 9 },
      { name: "CE333: Drawing & Detailing of RC Structures", credits: 3 },
    ],
    6: [
      { name: "CE334: Design of Steel Structure", credits: 8 },
      { name: "CE335: Drawing & Detailing of Steel Structures", credits: 2 },
      { name: "CE311: Open Channel Flow", credits: 8 },
      { name: "CE314: Open Channel Flow Laboratory", credits: 2 },
      { name: "DE-2: Departmental Elective (DE) - 2", credits: 9 },
      { name: "OE-2: Open Elective - 2", credits: 9 },
      { name: "CE392: Stream or UG Project", credits: 10 },
    ],
    7: [
      { name: "CE411: Engineering Hydrology", credits: 8 },
      { name: "DE-3: Departmental Elective (DE) - 3", credits: 9 },
      { name: "OE-3: Open Elective - 3", credits: 9 },
      { name: "CE431: Structural Engineering Laboratory", credits: 2 },
      { name: "LM: Language & Management Course", credits: 9 },
      { name: "CE491: Stream or UG Project", credits: 10 },
    ],
    8: [
      { name: "CE412: Irrigation Engineering", credits: 8 },
      { name: "CE432: Advanced Design of RC Structures", credits: 9 },
      { name: "DE-4: Departmental Elective - 4", credits: 9 },
      { name: "DE-5: Departmental Elective - 5", credits: 9 },
      { name: "OE-4: Open Elective - 4", credits: 9 },
      { name: "CE401: Construction Economics and Management", credits: 8 },
      { name: "LM: Language & Management Course", credits: 9 },
    ],
  },
  MET: {
    1: [
      {
        name: "PHY101: Physics – I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "CY101: Chemistry – I", credits: 10 },
      { name: "MA101: Engineering Mathematics – I", credits: 11 },
      { name: "ME103: Engineering Thermodynamics", credits: 11 },
      { name: "ME105: Manufacturing Practices– I", credits: 3 },
      { name: "ME104: Engineering Drawing", credits: 6 },
    ],
    2: [
      { name: "MA102: Engineering Mathematics – II", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      {
        name: "MT101: Introduction to Metallurgy and Materials Engineering",
        credits: 6,
      },
      { name: "MT102: Metallurgical Thermodynamics and Kinetics", credits: 11 },
      { name: "ME106: Manufacturing Practices – II", credits: 3 },
      { name: "MT103: Metallurgical Practices – I", credits: 3 },
      { name: "H103/H104/H105/H106: Humanities Elective", credits: 8 },
    ],
    3: [
      { name: "MA201: Numerical Techniques", credits: 11 },
      {
        name: "EO102: Fundamentals of Electronics and Instrumentation Engineering",
        credits: 13,
      },
      { name: "MT201: Structure of Materials", credits: 11 },
      { name: "MT202: Principles of Extractive Metallurgy", credits: 9 },
      { name: "MT203: Extractive Metallurgy Practical", credits: 3 },
      { name: "H103/H104/H105/H106: Humanities Elective", credits: 8 },
      { name: "MT291: Exploratory Project", credits: 5 },
    ],
    4: [
      { name: "MA203: Mathematical Methods", credits: 11 },
      { name: "MO102: Transport Phenomena", credits: 11 },
      { name: "MT204: Phase Diagrams", credits: 9 },
      { name: "MT205: Transport Phenomena Practical", credits: 3 },
      { name: "MT211: Iron Making Technologies", credits: 9 },
      { name: "MT221: Metallography Techniques", credits: 9 },
      { name: "MT222: Metallography Techniques Practical", credits: 3 },
      {
        name: "H201: Universal Human Values – II: Self, Society and Nature",
        credits: 5,
      },
    ],
    5: [
      { name: "MT301: Modelling and Simulation in Metallurgy", credits: 6 },
      {
        name: "MT302: Modelling and Simulation in Metallurgy Practical",
        credits: 3,
      },
      { name: "MT303: Deformation and Testing of Materials", credits: 9 },
      { name: "MT304: Materials Testing Practical", credits: 3 },
      { name: "MT321: Phase Transformations", credits: 9 },
      { name: "DE-1: Department Elective I", credits: 9 },
      { name: "OE-1: Open Elective I", credits: 9 },
      { name: "HU/LM-I: Humanities/Language & Management", credits: 9 },
    ],
    6: [
      { name: "MT307: Heat Treatment", credits: 6 },
      { name: "MT308: Heat Treatment Practical", credits: 3 },
      { name: "MT323: Mechanical Behaviour of Materials", credits: 9 },
      { name: "DE-2: Department Elective II", credits: 9 },
      { name: "OE-2: Open Elective II", credits: 9 },
      { name: "HU/LM-II: Humanities/Language & Management", credits: 9 },
      // UG/Stream Project and Composite Materials not included
    ],
    7: [
      { name: "MT401: Non-Ferrous Extractive Metallurgy", credits: 6 },
      { name: "MT411: Materials Processing Technologies", credits: 9 },
      {
        name: "MT412: Metallurgical Practices II: Materials Processing",
        credits: 2,
      },
      { name: "DE-3: Department Elective III", credits: 9 },
      { name: "OE-3: Open Elective III", credits: 9 },
      { name: "HU/LM-III: Humanities/Language & Management", credits: 9 },
      { name: "MT-491: UG Project", credits: 10 },
    ],
    8: [
      { name: "MT404: Corrosion and Prevention", credits: 6 },
      { name: "MT405: Electrometallurgy and Corrosion Practical", credits: 3 },
      { name: "MT414: Steel Making Technologies", credits: 9 },
      {
        name: "MT415: Metallurgical Practices-III: Ferrous Metallurgy",
        credits: 3,
      },
      { name: "DE-4: Department Elective IV", credits: 9 },
      { name: "OE-4: Open Elective IV", credits: 9 },
      { name: "HU/LM-IV: Humanities/Language & Management", credits: 9 },
    ],
  },
  MEC: {
    1: [
      {
        name: "PHY101: Physics - I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "MA101: Engineering Mathematics- I", credits: 11 },
      { name: "CY101: Chemistry - I", credits: 10 },
      { name: "ME103: Engineering Thermodynamics", credits: 11 },
      { name: "ME105: Manufacturing Practice I", credits: 3 },
      { name: "ME104: Engineering Drawing", credits: 6 },
    ],
    2: [
      { name: "MA102: Engineering Mathematics- II", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "ME102: Engineering Mechanics", credits: 11 },
      { name: "ME221: Mechanical Measurement", credits: 9 },
      { name: "ME106: Manufacturing Practice II", credits: 3 },
      { name: "ME222: Machine Drawing", credits: 3 },
      { name: "H105/H106: Philosophy or Education and Self", credits: 8 },
    ],
    3: [
      { name: "MA201: Numerical Techniques", credits: 11 },
      { name: "MO201: Materials Science", credits: 11 },
      { name: "ME201: Kinematics of Machines", credits: 9 },
      { name: "ME202: Fluid Mechanics", credits: 11 },
      { name: "ME203: Strength of Materials", credits: 11 },
      { name: "ME204: Manufacturing Processes", credits: 9 },
      {
        name: "H103/H104: Development of Societies or History and Civilization",
        credits: 8,
      },
    ],
    4: [
      { name: "MA203: Mathematical Methods", credits: 11 },
      { name: "ME205: Dynamics of Machines", credits: 9 },
      { name: "ME206: Heat and Mass Transfer", credits: 11 },
      { name: "ME207: Manufacturing Processes II", credits: 9 },
      { name: "ME208: Machine Design", credits: 9 },
      { name: "ME291: Exploratory Project", credits: 5 },
      { name: "H102: Universal Human Values-II", credits: 5 },
    ],
    5: [
      { name: "ME301: Internal Combustion Engines", credits: 9 },
      { name: "ME302: Refrigeration and Air Conditioning", credits: 9 },
      { name: "ME303: Control Engineering", credits: 9 },
      { name: "ME304: Operations Research", credits: 9 },
      { name: "DE-1: Department Elective – 1", credits: 9 },
      { name: "OE-1: Open Elective – 1", credits: 9 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
    6: [
      { name: "ME305: Computer Aided Design", credits: 9 },
      { name: "ME306: Mechatronics", credits: 9 },
      { name: "ME307: Finite Element Methods", credits: 9 },
      { name: "ME308: Industrial Engineering", credits: 9 },
      { name: "ME372: UG Project", credits: 10 },
      { name: "DE-2: Department Elective – 2", credits: 9 },
      { name: "OE-2: Open Elective – 2", credits: 9 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
    7: [
      { name: "ME401: Robotics", credits: 9 },
      { name: "ME402: Advanced Manufacturing Processes", credits: 9 },
      { name: "ME471: UG Project", credits: 10 },
      { name: "DE-3: Department Elective – 3", credits: 9 },
      { name: "OE-3: Open Elective – 3", credits: 9 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
    8: [
      { name: "ME403: Computational Fluid Dynamics", credits: 9 },
      { name: "ME404: Advanced Machine Design", credits: 9 },
      { name: "ME472: UG Project", credits: 10 },
      { name: "DE-4: Department Elective – 4", credits: 9 },
      { name: "OE-4: Open Elective – 4", credits: 9 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
  },
  ECE: {
    1: [
      {
        name: "PHY102: Physics-II Introduction to Engineering Electromagnetics",
        credits: 13,
      },
      { name: "CY101: Chemistry-I", credits: 10 },
      { name: "MA101: Engineering Mathematics-I", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "ME106: Manufacturing Practice-II", credits: 3 },
      { name: "ME104: Engineering Drawing", credits: 6 },
    ],
    2: [
      {
        name: "PHY101: Physics-I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "MA102: Engineering Mathematics- II", credits: 11 },
      { name: "EO101: Fundamentals of Electrical Engineering", credits: 13 },
      { name: "CSO102: Data Structures", credits: 11 },
      {
        name: "EC203: Electromagnetic Fields and Transmission Lines",
        credits: 9,
      },
      { name: "EC102: Electronic Circuit Workshop", credits: 6 },
      { name: "H105/H106: Philosophy or Education & Self", credits: 8 },
    ],
    3: [
      { name: "MA202: Probability and Statistics", credits: 11 },
      { name: "MO201: Materials Science", credits: 11 },
      { name: "EO201: Network Analysis & Synthesis", credits: 13 },
      { name: "EC201: Solid State Electronic Devices", credits: 9 },
      { name: "EC202: Signals and Systems", credits: 9 },
      { name: "EC271: Solid State Electronic Devices Lab", credits: 2 },
      {
        name: "H103/H104: Development of Societies or History and Civilization",
        credits: 8,
      },
    ],
    4: [
      { name: "ME101: Fundamentals of Mechanical Engineering", credits: 11 },
      { name: "EO202: Analogue Circuits and Systems", credits: 9 },
      { name: "EO203: Digital Circuits and Systems", credits: 9 },
      { name: "EC211: Analogue Communication Systems", credits: 9 },
      { name: "ME105: Manufacturing Practice – I", credits: 3 },
      { name: "EC291: Exploratory Project", credits: 5 },
      {
        name: "EC203: Electromagnetic Fields and Transmission Lines",
        credits: 9,
      },
      { name: "EO272: Analogue Circuits and Systems Lab", credits: 2 },
      { name: "EC273: Digital Circuits & Systems Lab", credits: 2 },
      { name: "EC274: Analogue Communication Systems Lab", credits: 2 },
    ],
    5: [
      { name: "EC341: Antennas and Propagation", credits: 9 },
      { name: "EC331: Microelectronics", credits: 9 },
      { name: "EC311: Digital Communication", credits: 9 },
      { name: "OE-1: Open Elective - 1", credits: 9 },
      { name: "EC321: Microprocessor Engineering", credits: 9 },
      { name: "EC371: Antennas and Propagation Lab", credits: 2 },
      { name: "EC372: Digital Communication Lab", credits: 2 },
      { name: "EC373: Microprocessor Engineering Lab", credits: 2 },
    ],
    6: [
      { name: "EC313: Digital Signal Processing", credits: 9 },
      { name: "EC342: Microwave Engineering", credits: 9 },
      { name: "EC392: UG Project", credits: 10 },
      { name: "DE-1: Department Elective (DE) - 1", credits: 9 },
      { name: "OE-2: Open Elective - 2", credits: 9 },
      {
        name: "EC322: Electronics Measurement and Instrumentation",
        credits: 9,
      },
    ],
    7: [
      { name: "EC411: Optical Communication", credits: 9 },
      { name: "EC431: Basic VLSI Design", credits: 9 },
      { name: "DE-2: Department Elective (DE) - 2", credits: 9 },
      { name: "OE-3: Open Elective - 3", credits: 9 },
      { name: "EC491: UG Project", credits: 10 },
      { name: "EC374: Microwave Engineering Lab", credits: 2 },
      { name: "LM: Language & Management Courses", credits: 9 },
    ],
    8: [
      { name: "DE-3: Department Elective (DE) - 3", credits: 9 },
      { name: "DE-4: Department Elective (DE) - 4", credits: 9 },
      { name: "DE-5: Department Elective (DE) - 5", credits: 9 },
      { name: "OE-4: Open Elective - 4", credits: 9 },
      { name: "LM: Language & Management Courses", credits: 9 },
    ],
  },
  EEE: {
    1: [
      {
        name: "PHY102: Physics-II Introduction to Engineering Electromagnetics",
        credits: 13,
      },
      { name: "CY101: Chemistry-I", credits: 10 },
      { name: "MA101: Engineering Maths- I", credits: 11 },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "ME106: Manufacturing Practice-II", credits: 3 },
      { name: "ME104: Engineering Drawing", credits: 6 },
    ],
    2: [
      { name: "MA203: Mathematical Methods", credits: 11 },
      { name: "MO201: Material Science", credits: 11 },
      {
        name: "EO102: Fundamentals of Electronics & Instrumentation Engineering",
        credits: 13,
      },
      { name: "EE101: Electrical Circuits and Measurement", credits: 13 },
      { name: "ME105: Manufacturing Practice – I", credits: 3 },
      { name: "H105/H106: Philosophy or Education & Self", credits: 8 },
    ],
    3: [
      { name: "MA201: Numerical Techniques", credits: 11 },
      { name: "CMO101: Basics of Mechanical Engineering", credits: 11 },
      { name: "EO201: Network Analysis & Synthesis", credits: 11 },
      { name: "EE221: DC Machines & Transformer", credits: 13 },
      { name: "EE261: Electrical Engineering Practice", credits: 5 },
      {
        name: "H103/H104: Development of Societies or History and Civilization",
        credits: 8,
      },
    ],
    4: [
      { name: "MA202: Probability and Statistics", credits: 11 },
      { name: "EE241: Power Transmission & Distribution", credits: 13 },
      { name: "EE231: Power Electronic Devices & Converters", credits: 13 },
      { name: "EE211: Linear Control Systems", credits: 13 },
      { name: "EE272: Exploratory Project", credits: 5 },
      { name: "H102: Universal Human Value-II", credits: 5 },
    ],
    5: [
      { name: "EO301: Digital Circuits & Systems", credits: 11 },
      { name: "EE342: Power System Protection and Switchgear", credits: 11 },
      { name: "EE322: Synchronous and Induction Machines", credits: 11 },
      { name: "OE-1: Open Elective-1", credits: 9 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
    6: [
      { name: "EE343: Power System Analysis & Control", credits: 11 },
      {
        name: "EE332: Analysis & Applications of Power Electronic Converters",
        credits: 11,
      },
      {
        name: "EE323: Condition Monitoring and Energy Conservation",
        credits: 9,
      },
      { name: "OE-2: Open Elective-2", credits: 9 },
      { name: "EE372: UG Project", credits: 10 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
    7: [
      { name: "EE401: Design & Simulation of Electrical Systems", credits: 8 },
      { name: "EE413: Digital Control System", credits: 9 },
      { name: "OE-3: Open Elective-3", credits: 9 },
      { name: "EE471: UG Project", credits: 10 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
    8: [
      { name: "EE447: High Voltage Engineering", credits: 11 },
      { name: "EE414: Optimal and Adaptive Control System", credits: 9 },
      { name: "OE-4: Open Elective-4", credits: 9 },
      { name: "HU/LM: Humanities/Language & Management", credits: 9 },
    ],
  },
  PHE: {
    1: [
      { name: "BL101: Biology", credits: 11 },
      { name: "CY101: Chemistry – I", credits: 10 },
      {
        name: "PHY102: Physics – II: Introduction to Engineering Electromagnetics",
        credits: 13,
      },
      { name: "CMO103: Engineering Thermodynamics", credits: 11 },
      { name: "ME104: Engineering Drawing", credits: 6 },
      { name: "ME105: Manufacturing Practice – I", credits: 3 },
    ],
    2: [
      { name: "MA101: Engineering Mathematics – I", credits: 11 },
      { name: "CY103: Essentials of Biochemistry", credits: 11 },
      { name: "PH101: Basics of Pharmaceutical Sciences", credits: 9 },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "ME106: Manufacturing Practice – II", credits: 3 },
      {
        name: "H103/H104/H105/H106: Development of Societies/History & Civilization/Philosophy/Education & Self",
        credits: 8,
      },
    ],
    3: [
      { name: "MO201: Materials Science", credits: 11 },
      { name: "BO202: Human Physiology", credits: 9 },
      { name: "MA202: Probability and Statistics", credits: 11 },
      { name: "PH211: Physical Pharmaceutics", credits: 9 },
      { name: "PH221: Pharmaceutical Chemistry", credits: 9 },
      {
        name: "H103/H104/H105/H106: Development of Societies/History & Civilization/Philosophy/Education & Self",
        credits: 8,
      },
    ],
    4: [
      { name: "CMO103: Heat and Mass Transfer", credits: 11 },
      { name: "PH222: Bioorganic and Medicinal Chemistry", credits: 9 },
      { name: "PH231: General Pharmacology", credits: 11 },
      { name: "PH241: General Pharmacognosy", credits: 9 },
      { name: "PH251: Pharmaceutical Analysis", credits: 8 },
      { name: "PH291: Exploratory Project", credits: 5 },
      {
        name: "HL201: Universal Human Values - II: Self, Society and Family",
        credits: 5,
      },
    ],
    5: [
      { name: "Open Elective I", credits: 9 },
      { name: "BO301: Microbiology and Biotechnology", credits: 9 },
      { name: "PH311: Pharmaceutical Technology", credits: 11 },
      { name: "PH331: General Pharmacotherapeutics", credits: 9 },
      { name: "PH341: Natural Drugs and Excipients", credits: 8 },
      { name: "Language & Management/Humanities Course", credits: 9 },
    ],
    6: [
      { name: "Open Elective II", credits: 9 },
      { name: "PH301: Pharmaceutical Jurisprudence", credits: 6 },
      { name: "PH321: Chemistry of Synthetic Drugs", credits: 9 },
      { name: "PH312/PH322/PH332/PH342: Core/Bouquet Elective I", credits: 11 },
      { name: "PH392: Regular Stream Project", credits: 10 },
      { name: "Language & Management/Humanities Course", credits: 9 },
    ],
    7: [
      { name: "Open Elective III", credits: 9 },
      { name: "PH451: Pharmaceutical Instrumental Analysis", credits: 9 },
      { name: "PH411/PH421/PH432/PH441/PH452: Core Elective II", credits: 9 },
      { name: "PH511/PH521/PH531/PH541: Core Elective III", credits: 9 },
      { name: "PH491: Regular Stream Project", credits: 10 },
      { name: "Language & Management/Humanities Course", credits: 9 },
    ],
    8: [
      { name: "Open Elective IV", credits: 9 },
      { name: "PH412: Dosage Formulation Design", credits: 9 },
      { name: "PH442: Analytical Pharmacognosy", credits: 9 },
      { name: "PH413/PH422/PH433/PH443/PH453: Core Elective IV", credits: 9 },
      { name: "H401: Language & Management/Humanities Course", credits: 9 },
    ],
  },
  MIN: {
    1: [
      {
        name: "PHY101: Physics - I: Classical, Quantum & Relativistic Mechanics",
        credits: 13,
      },
      { name: "CY101: Chemistry – I", credits: 10 },
      { name: "MA102: Engineering Mathematics – II", credits: 11 },
      { name: "ME102: Engineering Mechanics", credits: 11 },
      { name: "ME105: Manufacturing Practice – I", credits: 3 },
      { name: "ME104: Engineering Drawing", credits: 6 },
    ],
    2: [
      { name: "MA101: Engineering Mathematics – I", credits: 11 },
      {
        name: "EO102: Fundamentals of Electronics and Instrumentation Engineering",
        credits: 13,
      },
      { name: "CSO101: Computer Programming", credits: 13 },
      { name: "MN111: Mine Development", credits: 6 },
      { name: "MN112: Mine Practices", credits: 6 },
      { name: "ME106: Manufacturing Practice – II", credits: 3 },
      {
        name: "H103/H104: Development of Societies or History and Civilization",
        credits: 8,
      },
    ],
    3: [
      { name: "MN2101: Mining Geology – I", credits: 4 },
      { name: "MN2102: Mine Surveying – I", credits: 3 },
      { name: "MN2103: Underground Mine Environment – I", credits: 3 },
      { name: "MN2104: Mining Machinery – I", credits: 3 },
      { name: "MN2105: Mine Development", credits: 4 },
      { name: "EC2108A: Electronics and Instrumentation", credits: 3 },
      { name: "MN2301: Mining Geology – I (Practical)", credits: 2 },
      { name: "MN2302: Mine Surveying – I (Practical)", credits: 2 },
      {
        name: "MN2303: Underground Mine Environment – I (Practical)",
        credits: 2,
      },
    ],
    4: [
      { name: "MN2201: Mining Geology – II", credits: 3 },
      { name: "MN2202: Rock Mechanics", credits: 4 },
      { name: "MN2203: Mining Machinery – II", credits: 3 },
      { name: "AM2208A: Numerical Methods", credits: 3 },
      { name: "EE2208A: Electrical Engineering – I", credits: 3 },
      { name: "MN2401: Mining Geology – II (Practical)", credits: 2 },
      { name: "MN2402: Rock Mechanics (Practical)", credits: 2 },
      { name: "EE2408A: Electrical Engineering (Practical)", credits: 2 },
      { name: "MN2403: Tour Report & Viva-Voce", credits: 2 },
    ],
    5: [
      { name: "MN3101: Ground Control", credits: 3 },
      { name: "MN3102: Underground Mine Environment – II", credits: 3 },
      { name: "MN3103: Mine Surveying – II", credits: 3 },
      { name: "MN3104: Underground Coal Mining – I", credits: 4 },
      { name: "MN3105: Surface Mining – I", credits: 3 },
      { name: "EE3108A: Electrical Engineering – II", credits: 3 },
      { name: "MN3301: Ground Control (Practical)", credits: 2 },
      {
        name: "MN3302: Underground Mine Environment – II (Practical)",
        credits: 2,
      },
      { name: "MN3303: Mine Surveying – II (Practical)", credits: 2 },
    ],
    6: [
      { name: "MN3201: Mineral Processing", credits: 4 },
      { name: "MN3202: Environmental Management in Surface Mines", credits: 4 },
      { name: "MN3203: Underground Coal Mining - II", credits: 3 },
      { name: "MN3204: Surface Mining – II", credits: 3 },
      { name: "MN3205: Computer Applications in Mining", credits: 3 },
      { name: "Open Elective (Humanities)", credits: 3 },
      { name: "MN3401: Mineral Processing (Practical)", credits: 2 },
      {
        name: "MN3402: Environmental Management in Surface Mines (Practical)",
        credits: 2,
      },
      { name: "MN3403: Mining Machinery (Practical)", credits: 2 },
    ],
    7: [
      { name: "MN4103: Mining Machinery – III", credits: 3 },
      { name: "MN4104: Mine Disasters", credits: 3 },
      { name: "MN5103: Project Management", credits: 3 },
      { name: "Elective – 1", credits: 3 },
      { name: "Elective – 2", credits: 4 },
      {
        name: "MN4301: Computer Application in Mine Planning (Practical)",
        credits: 2,
      },
      { name: "MN4303: Seminar / Group Discussion", credits: 2 },
      // UG Project, Training Report, and Stream Hons. not included
    ],
    8: [
      { name: "MN4201: Underground Metalliferous Mining", credits: 3 },
      { name: "MN4202: Mine Legislation", credits: 4 },
      { name: "MN5201: Underground Mine Planning", credits: 3 },
      { name: "Elective – 1", credits: 3 },
      { name: "Elective – 2", credits: 3 },
      {
        name: "MN4401: Underground Metalliferous Mining (Practical)",
        credits: 2,
      },
      { name: "MN5411: Rock Mechanics (Practical)", credits: 2 },
      { name: "MN4432: Comprehensive Viva-Voce", credits: 2 },
    ],
  },
};
